-- 見本データのエリアを36に増やし、新しい31エリアに宿1・レジャー1の施設と料金プランを入れる（issue #9）
-- 001〜006 のあとに実行する。何度実行しても同じ結果になる
-- 施設名は実在の施設。住所は市区町村まで、説明は一般的な表現、料金・外部の評価はダミー。口コミ・周辺スポットは入れない

-- ① エリア（北から南の順）。既にあるエリアは名前・地方・並び順を合わせる
insert into bts_app.areas (tenant_id, code, name, region, sort)
select null::uuid, v.code, v.name, v.region, v.sort
from (values
  ('furano', '富良野・旭川', '北海道', 1),
  ('sapporo', '札幌', '北海道', 2),
  ('noboribetsu', '登別', '北海道', 3),
  ('hakodate', '函館', '北海道', 4),
  ('aomori', '青森・奥入瀬', '東北', 5),
  ('sendai', '仙台', '東北', 6),
  ('zao', '蔵王', '東北', 7),
  ('aizu', '会津・磐梯', '東北', 8),
  ('nasu', '那須', '関東', 9),
  ('nikko', '日光', '関東', 10),
  ('kusatsu', '草津', '関東', 11),
  ('tokyo', '東京', '関東', 12),
  ('yokohama', '横浜', '関東', 13),
  ('hakone', '箱根', '関東', 14),
  ('atami', '熱海', '関東', 15),
  ('izu', '伊豆', '関東', 16),
  ('karuizawa', '軽井沢', '中部', 17),
  ('fujigoko', '富士五湖', '中部', 18),
  ('kanazawa', '金沢', '中部', 19),
  ('takayama', '飛騨高山', '中部', 20),
  ('gero', '下呂', '中部', 21),
  ('nagoya', '名古屋', '中部', 22),
  ('kinosaki', '城崎', '関西', 23),
  ('kyoto', '京都', '関西', 24),
  ('kobe', '神戸・有馬', '関西', 25),
  ('osaka', '大阪', '関西', 26),
  ('nara', '奈良', '関西', 27),
  ('ise', '伊勢志摩', '関西', 28),
  ('shirahama', '南紀白浜', '関西', 29),
  ('matsue', '松江・出雲', '中国・四国', 30),
  ('hiroshima', '広島・宮島', '中国・四国', 31),
  ('dogo', '松山・道後', '中国・四国', 32),
  ('beppu', '別府', '九州・沖縄', 33),
  ('nagasaki', '長崎・佐世保', '九州・沖縄', 34),
  ('okinawa', '沖縄', '九州・沖縄', 35),
  ('ishigaki', '石垣島', '九州・沖縄', 36)
) as v(code, name, region, sort)
where not exists (select 1 from bts_app.areas a where a.code = v.code and a.tenant_id is null);

update bts_app.areas a set name = v.name, region = v.region, sort = v.sort, updated_at = now()
from (values
  ('furano', '富良野・旭川', '北海道', 1),
  ('sapporo', '札幌', '北海道', 2),
  ('noboribetsu', '登別', '北海道', 3),
  ('hakodate', '函館', '北海道', 4),
  ('aomori', '青森・奥入瀬', '東北', 5),
  ('sendai', '仙台', '東北', 6),
  ('zao', '蔵王', '東北', 7),
  ('aizu', '会津・磐梯', '東北', 8),
  ('nasu', '那須', '関東', 9),
  ('nikko', '日光', '関東', 10),
  ('kusatsu', '草津', '関東', 11),
  ('tokyo', '東京', '関東', 12),
  ('yokohama', '横浜', '関東', 13),
  ('hakone', '箱根', '関東', 14),
  ('atami', '熱海', '関東', 15),
  ('izu', '伊豆', '関東', 16),
  ('karuizawa', '軽井沢', '中部', 17),
  ('fujigoko', '富士五湖', '中部', 18),
  ('kanazawa', '金沢', '中部', 19),
  ('takayama', '飛騨高山', '中部', 20),
  ('gero', '下呂', '中部', 21),
  ('nagoya', '名古屋', '中部', 22),
  ('kinosaki', '城崎', '関西', 23),
  ('kyoto', '京都', '関西', 24),
  ('kobe', '神戸・有馬', '関西', 25),
  ('osaka', '大阪', '関西', 26),
  ('nara', '奈良', '関西', 27),
  ('ise', '伊勢志摩', '関西', 28),
  ('shirahama', '南紀白浜', '関西', 29),
  ('matsue', '松江・出雲', '中国・四国', 30),
  ('hiroshima', '広島・宮島', '中国・四国', 31),
  ('dogo', '松山・道後', '中国・四国', 32),
  ('beppu', '別府', '九州・沖縄', 33),
  ('nagasaki', '長崎・佐世保', '九州・沖縄', 34),
  ('okinawa', '沖縄', '九州・沖縄', 35),
  ('ishigaki', '石垣島', '九州・沖縄', 36)
) as v(code, name, region, sort)
where a.code = v.code and a.tenant_id is null
  and (a.name, a.region, a.sort) is distinct from (v.name, v.region, v.sort);

-- ② 施設（menus）。同じ会社に同じ名前の施設があれば入れない
insert into bts_app.menus (tenant_id, area_id, name, category, address, description, usage_limit, family_scope, cancel_policy, hotel_ref, matched, content_updated_at, tags)
select t.id, a.id, v.name, v.category, v.address, v.description, v.usage_limit, v.family_scope, v.cancel_policy, v.hotel_ref, v.hotel_ref is not null, v.content_updated_at::date, v.tags
from (values
  ('furano', '新富良野プリンスホテル', 'stay', '北海道富良野市', '富良野の森の中に建つリゾートホテル。ニングルテラスに隣接', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-FURANO', '2026-09-01', array['森', '自然', '高原', 'スキー']),
  ('furano', '旭山動物園', 'leisure', '北海道旭川市', '動物の行動を見せる展示で知られる動物園', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-01', array['動物園', '子ども', '家族向け']),
  ('sapporo', 'JRタワーホテル日航札幌', 'stay', '北海道札幌市中央区', '札幌駅直結の高層ホテル。展望の天然温泉スパ', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-SAPPORO', '2026-09-02', array['駅直結', '街歩き', '温泉', '夜景']),
  ('sapporo', '白い恋人パーク', 'leisure', '北海道札幌市西区', 'お菓子づくりの見学と体験ができる施設', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-02', array['工場見学', '体験', '子ども', '雨の日']),
  ('noboribetsu', '登別温泉 第一滝本館', 'stay', '北海道登別市', '地獄谷の近くにある大浴場の温泉宿', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-NOBORIBETSU', '2026-09-03', array['温泉', '大浴場', '家族向け']),
  ('noboribetsu', '登別マリンパークニクス', 'leisure', '北海道登別市', '城の形をした水族館のある海のテーマパーク', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-03', array['水族館', '子ども', '雨の日']),
  ('hakodate', 'ラビスタ函館ベイ', 'stay', '北海道函館市', 'ベイエリアの温泉ホテル。朝食が人気', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-HAKODATE', '2026-09-04', array['温泉', '露天風呂', '海', '街歩き']),
  ('hakodate', '函館山ロープウェイ', 'leisure', '北海道函館市', '山頂から函館の夜景を一望', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-04', array['夜景', '絶景', '観光']),
  ('aomori', '星野リゾート 奥入瀬渓流ホテル', 'stay', '青森県十和田市', '奥入瀬渓流沿いに建つ温泉リゾート', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-AOMORI', '2026-09-05', array['温泉', '自然', '渓流', '絶景']),
  ('aomori', '八甲田ロープウェー', 'leisure', '青森県青森市', '八甲田の山頂公園まで約10分の空中散歩', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-05', array['絶景', '自然', '紅葉']),
  ('sendai', '仙台国際ホテル', 'stay', '宮城県仙台市青葉区', '仙台駅から徒歩圏のシティホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-SENDAI', '2026-09-06', array['駅近', '街歩き', '観光']),
  ('sendai', '仙台うみの杜水族館', 'leisure', '宮城県仙台市宮城野区', '三陸の海をテーマにした水族館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-06', array['水族館', '子ども', '雨の日']),
  ('zao', '蔵王国際ホテル', 'stay', '山形県山形市', '蔵王温泉の硫黄泉を楽しめる宿', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-ZAO', '2026-09-07', array['温泉', '露天風呂', 'スキー', '高原']),
  ('zao', '蔵王ロープウェイ', 'leisure', '山形県山形市', '冬は樹氷、夏は高原の景色を楽しめる', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-07', array['絶景', '自然', 'スキー']),
  ('aizu', '星野リゾート 磐梯山温泉ホテル', 'stay', '福島県耶麻郡磐梯町', '磐梯山のふもとの温泉リゾート', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-AIZU', '2026-09-08', array['温泉', '自然', '家族向け', 'スキー']),
  ('aizu', '鶴ヶ城（若松城天守閣）', 'leisure', '福島県会津若松市', '赤瓦の天守閣と郷土博物館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-08', array['観光', '歴史', '城']),
  ('nasu', 'ホテルエピナール那須', 'stay', '栃木県那須郡那須町', '家族向けのイベントが多い高原リゾート', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-NASU', '2026-09-09', array['温泉', '家族向け', '子ども', '高原', 'プール']),
  ('nasu', '那須ハイランドパーク', 'leisure', '栃木県那須郡那須町', '高原にある遊園地', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-09', array['テーマパーク', '子ども', '家族向け']),
  ('nikko', '日光金谷ホテル', 'stay', '栃木県日光市', '明治創業のクラシックホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-NIKKO', '2026-09-10', array['歴史', '観光', '静か']),
  ('nikko', '東武ワールドスクウェア', 'leisure', '栃木県日光市', '世界の建築物を25分の1で再現したテーマパーク', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-10', array['テーマパーク', '観光', '子ども']),
  ('kusatsu', '草津ナウリゾートホテル', 'stay', '群馬県吾妻郡草津町', '高原の露天風呂とビュッフェのホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-KUSATSU', '2026-09-11', array['温泉', '露天風呂', '高原', '家族向け']),
  ('kusatsu', '西の河原露天風呂', 'leisure', '群馬県吾妻郡草津町', '公園の中にある大きな露天風呂', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-11', array['温泉', '露天風呂', '自然']),
  ('tokyo', 'ホテル椿山荘東京', 'stay', '東京都文京区', '庭園に囲まれたホテル。雲海の演出が名物', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-TOKYO', '2026-09-12', array['庭園', '記念日', '高級', '街歩き']),
  ('tokyo', '東京スカイツリー', 'leisure', '東京都墨田区', '高さ350mと450mの展望台から東京を一望', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-12', array['展望', '夜景', '観光', '雨の日']),
  ('yokohama', '横浜ベイホテル東急', 'stay', '神奈川県横浜市西区', 'みなとみらいの海に面したホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-YOKOHAMA', '2026-09-13', array['海', '夜景', '街歩き', '駅近']),
  ('yokohama', '横浜・八景島シーパラダイス', 'leisure', '神奈川県横浜市金沢区', '水族館と遊園地の島', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-13', array['水族館', 'テーマパーク', '子ども', '海']),
  ('izu', '東府や Resort & Spa-Izu', 'stay', '静岡県伊豆市', '修善寺の森の中の温泉リゾート', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-IZU', '2026-09-14', array['温泉', '足湯', '森', '静か']),
  ('izu', '伊豆シャボテン動物公園', 'leisure', '静岡県伊東市', 'カピバラの露天風呂で知られる動物園', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-14', array['動物園', '子ども', '家族向け']),
  ('fujigoko', 'ハイランドリゾート ホテル＆スパ', 'stay', '山梨県富士吉田市', '富士急ハイランドに隣接し、富士山を望むホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-FUJIGOKO', '2026-09-15', array['富士山', '絶景', 'テーマパーク', '子ども', '温泉']),
  ('fujigoko', '富士急ハイランド', 'leisure', '山梨県富士吉田市', '絶叫マシンで知られる遊園地', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-15', array['テーマパーク', '子ども', '富士山']),
  ('kanazawa', 'ハイアット セントリック 金沢', 'stay', '石川県金沢市', '金沢駅前のホテル。屋上テラスあり', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-KANAZAWA', '2026-09-16', array['駅近', '街歩き', '観光']),
  ('kanazawa', '金沢21世紀美術館', 'leisure', '石川県金沢市', '体験型の展示が多い現代美術館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-16', array['美術館', '観光', '雨の日']),
  ('takayama', '本陣平野屋 花兆庵', 'stay', '岐阜県高山市', '古い町並みに近い温泉旅館', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-TAKAYAMA', '2026-09-17', array['温泉', '旅館', '街歩き', '部屋食']),
  ('takayama', '飛騨の里', 'leisure', '岐阜県高山市', '合掌造りの民家を集めた野外博物館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-17', array['観光', '歴史', '自然']),
  ('gero', '下呂温泉 水明館', 'stay', '岐阜県下呂市', '飛騨川沿いの大型温泉旅館', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-GERO', '2026-09-18', array['温泉', '露天風呂', '旅館', '大浴場']),
  ('gero', '下呂温泉合掌村', 'leisure', '岐阜県下呂市', '合掌造りの集落を移築した施設', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-18', array['観光', '歴史', '体験']),
  ('nagoya', '名古屋マリオットアソシアホテル', 'stay', '愛知県名古屋市中村区', '名古屋駅直結の高層ホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-NAGOYA', '2026-09-19', array['駅直結', '夜景', '街歩き']),
  ('nagoya', 'レゴランド・ジャパン', 'leisure', '愛知県名古屋市港区', 'レゴブロックの世界を楽しむテーマパーク', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-19', array['テーマパーク', '子ども', '家族向け']),
  ('kinosaki', '城崎温泉 西村屋本館', 'stay', '兵庫県豊岡市', '外湯めぐりの起点になる老舗旅館', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-KINOSAKI', '2026-09-20', array['温泉', '旅館', '外湯', '庭園']),
  ('kinosaki', '城崎マリンワールド', 'leisure', '兵庫県豊岡市', '日本海に面した体験型の水族館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-20', array['水族館', '子ども', '海']),
  ('kobe', '有馬温泉 兵衛向陽閣', 'stay', '兵庫県神戸市北区', '金泉と銀泉の両方に入れる温泉旅館', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-KOBE', '2026-09-21', array['温泉', '露天風呂', '旅館', '家族向け']),
  ('kobe', '神戸どうぶつ王国', 'leisure', '兵庫県神戸市中央区', '花と動物にふれあえる屋内型の施設', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-21', array['動物園', '子ども', '雨の日']),
  ('osaka', 'ホテル京阪 ユニバーサル・タワー', 'stay', '大阪府大阪市此花区', 'ユニバーサル・スタジオ・ジャパンの近くのホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-OSAKA', '2026-09-22', array['テーマパーク', '子ども', '家族向け', '駅近']),
  ('osaka', 'ユニバーサル・スタジオ・ジャパン', 'leisure', '大阪府大阪市此花区', '映画やゲームの世界を楽しむテーマパーク', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-22', array['テーマパーク', '子ども', '家族向け']),
  ('nara', '奈良ホテル', 'stay', '奈良県奈良市', '明治創業のクラシックホテル。奈良公園に近い', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-NARA', '2026-09-23', array['歴史', '観光', '静か', '公園']),
  ('nara', '奈良国立博物館', 'leisure', '奈良県奈良市', '仏教美術を中心とした博物館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-23', array['美術館', '歴史', '雨の日']),
  ('ise', '志摩観光ホテル', 'stay', '三重県志摩市', '英虞湾を望むリゾートホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-ISE', '2026-09-24', array['海', '絶景', '記念日', '高級']),
  ('ise', '志摩スペイン村', 'leisure', '三重県志摩市', 'スペインの街並みのテーマパーク', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-24', array['テーマパーク', '子ども', '温泉']),
  ('shirahama', 'ホテル川久', 'stay', '和歌山県西牟婁郡白浜町', '宮殿のような建築のリゾートホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-SHIRAHAMA', '2026-09-25', array['海', '絶景', '記念日', '高級']),
  ('shirahama', 'アドベンチャーワールド', 'leisure', '和歌山県西牟婁郡白浜町', '動物園・水族館・遊園地が一体のテーマパーク', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-25', array['動物園', '水族館', 'テーマパーク', '子ども']),
  ('matsue', '玉造温泉 長楽園', 'stay', '島根県松江市', '大きな混浴の露天風呂がある老舗旅館', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-MATSUE', '2026-09-26', array['温泉', '露天風呂', '旅館', '庭園']),
  ('matsue', '足立美術館', 'leisure', '島根県安来市', '日本庭園と近代日本画で知られる美術館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-26', array['美術館', '庭園', '雨の日']),
  ('hiroshima', '宮島 錦水館', 'stay', '広島県廿日市市', '宮島の表参道に面した旅館', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-HIROSHIMA', '2026-09-27', array['温泉', '旅館', '観光', '海']),
  ('hiroshima', '宮島水族館 みやじマリン', 'leisure', '広島県廿日市市', '瀬戸内海の生き物を中心とした水族館', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-27', array['水族館', '子ども', '雨の日']),
  ('dogo', '道後温泉 ふなや', 'stay', '愛媛県松山市', '道後温泉本館の近くの老舗旅館', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-DOGO', '2026-09-28', array['温泉', '旅館', '庭園', '街歩き']),
  ('dogo', '松山城', 'leisure', '愛媛県松山市', 'ロープウェイで登る現存天守の城', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-28', array['観光', '歴史', '城', '絶景']),
  ('beppu', '杉乃井ホテル', 'stay', '大分県別府市', '棚田状の露天風呂と大型プールのあるホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-BEPPU', '2026-09-01', array['温泉', '露天風呂', 'プール', '家族向け', '子ども']),
  ('beppu', '別府地獄めぐり', 'leisure', '大分県別府市', '色や形の異なる7つの地獄（源泉）をめぐる', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-01', array['温泉', '観光', '自然']),
  ('nagasaki', 'ホテルニュー長崎', 'stay', '長崎県長崎市', '長崎駅前のシティホテル', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-NAGASAKI', '2026-09-02', array['駅近', '街歩き', '夜景']),
  ('nagasaki', 'ハウステンボス', 'leisure', '長崎県佐世保市', 'ヨーロッパの街並みのテーマパーク', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-02', array['テーマパーク', '子ども', '夜景', '花']),
  ('ishigaki', 'ANAインターコンチネンタル石垣リゾート', 'stay', '沖縄県石垣市', '真栄里ビーチに面したリゾート', '年2回まで', '本人と2親等まで', '7日前まで無料', 'H-ISHIGAKI', '2026-09-03', array['海', 'ビーチ', 'リゾート', 'プール', '子ども']),
  ('ishigaki', '川平湾グラスボート', 'leisure', '沖縄県石垣市', '船底のガラスからサンゴと熱帯魚を見る', '年3回まで', '本人と2親等まで', '当日可', null, '2026-09-03', array['海', '絶景', '子ども', '自然'])
) as v(area_code, name, category, address, description, usage_limit, family_scope, cancel_policy, hotel_ref, content_updated_at, tags)
join bts_app.tenants t on t.code = 'sample'
join bts_app.areas a on a.code = v.area_code and a.tenant_id is null
where not exists (select 1 from bts_app.menus m where m.tenant_id = t.id and m.name = v.name);

-- ③ 料金プラン（plans）。施設は名前で探し、同じ施設に同じ名前のプランがあれば入れない
insert into bts_app.plans (menu_id, name, room_type, meal, grade, adults, children, nights, list_price, benefit_price, coupon_code, member_url)
select m.id, v.name, v.room_type, v.meal, v.grade, v.adults, v.children, v.nights, v.list_price, v.benefit_price, v.coupon_code, v.member_url
from (values
  ('新富良野プリンスホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 30000, 21600, 'H-FURANO-1', 'https://example.com/member/h-furano'),
  ('新富良野プリンスホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 42000, 33600, 'H-FURANO-2', 'https://example.com/member/h-furano'),
  ('旭山動物園', '入場（大人1名）', null, null, null, 1, 0, 1, 1000, 800, 'L-FURANO-1', 'https://example.com/member/l-furano'),
  ('JRタワーホテル日航札幌', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 36000, 25200, 'H-SAPPORO-1', 'https://example.com/member/h-sapporo'),
  ('JRタワーホテル日航札幌', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 50400, 39300, 'H-SAPPORO-2', 'https://example.com/member/h-sapporo'),
  ('白い恋人パーク', '入場（大人1名）', null, null, null, 1, 0, 1, 800, 600, 'L-SAPPORO-1', 'https://example.com/member/l-sapporo'),
  ('登別温泉 第一滝本館', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 28000, 19600, 'H-NOBORIBETSU-1', 'https://example.com/member/h-noboribetsu'),
  ('登別温泉 第一滝本館', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 39200, 30600, 'H-NOBORIBETSU-2', 'https://example.com/member/h-noboribetsu'),
  ('登別マリンパークニクス', '入場（大人1名）', null, null, null, 1, 0, 1, 2800, 2100, 'L-NOBORIBETSU-1', 'https://example.com/member/l-noboribetsu'),
  ('ラビスタ函館ベイ', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 34000, 22100, 'H-HAKODATE-1', 'https://example.com/member/h-hakodate'),
  ('ラビスタ函館ベイ', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 47600, 34700, 'H-HAKODATE-2', 'https://example.com/member/h-hakodate'),
  ('函館山ロープウェイ', '入場（大人1名）', null, null, null, 1, 0, 1, 1800, 1400, 'L-HAKODATE-1', 'https://example.com/member/l-hakodate'),
  ('星野リゾート 奥入瀬渓流ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 42000, 27300, 'H-AOMORI-1', 'https://example.com/member/h-aomori'),
  ('星野リゾート 奥入瀬渓流ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 58800, 42900, 'H-AOMORI-2', 'https://example.com/member/h-aomori'),
  ('八甲田ロープウェー', '入場（大人1名）', null, null, null, 1, 0, 1, 2300, 1700, 'L-AOMORI-1', 'https://example.com/member/l-aomori'),
  ('仙台国際ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 24000, 14900, 'H-SENDAI-1', 'https://example.com/member/h-sendai'),
  ('仙台国際ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 33600, 23500, 'H-SENDAI-2', 'https://example.com/member/h-sendai'),
  ('仙台うみの杜水族館', '入場（大人1名）', null, null, null, 1, 0, 1, 2400, 1800, 'L-SENDAI-1', 'https://example.com/member/l-sendai'),
  ('蔵王国際ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 32000, 22400, 'H-ZAO-1', 'https://example.com/member/h-zao'),
  ('蔵王国際ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 44800, 34900, 'H-ZAO-2', 'https://example.com/member/h-zao'),
  ('蔵王ロープウェイ', '入場（大人1名）', null, null, null, 1, 0, 1, 3800, 2800, 'L-ZAO-1', 'https://example.com/member/l-zao'),
  ('星野リゾート 磐梯山温泉ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 30000, 21600, 'H-AIZU-1', 'https://example.com/member/h-aizu'),
  ('星野リゾート 磐梯山温泉ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 42000, 33600, 'H-AIZU-2', 'https://example.com/member/h-aizu'),
  ('鶴ヶ城（若松城天守閣）', '入場（大人1名）', null, null, null, 1, 0, 1, 410, 300, 'L-AIZU-1', 'https://example.com/member/l-aizu'),
  ('ホテルエピナール那須', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 30000, 18600, 'H-NASU-1', 'https://example.com/member/h-nasu'),
  ('ホテルエピナール那須', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 42000, 29400, 'H-NASU-2', 'https://example.com/member/h-nasu'),
  ('那須ハイランドパーク', '入場（大人1名）', null, null, null, 1, 0, 1, 1800, 1400, 'L-NASU-1', 'https://example.com/member/l-nasu'),
  ('日光金谷ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 38000, 26600, 'H-NIKKO-1', 'https://example.com/member/h-nikko'),
  ('日光金谷ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 53200, 41500, 'H-NIKKO-2', 'https://example.com/member/h-nikko'),
  ('東武ワールドスクウェア', '入場（大人1名）', null, null, null, 1, 0, 1, 2800, 2100, 'L-NIKKO-1', 'https://example.com/member/l-nikko'),
  ('草津ナウリゾートホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 26000, 16100, 'H-KUSATSU-1', 'https://example.com/member/h-kusatsu'),
  ('草津ナウリゾートホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 36400, 25500, 'H-KUSATSU-2', 'https://example.com/member/h-kusatsu'),
  ('西の河原露天風呂', '入場（大人1名）', null, null, null, 1, 0, 1, 700, 500, 'L-KUSATSU-1', 'https://example.com/member/l-kusatsu'),
  ('ホテル椿山荘東京', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 64000, 46100, 'H-TOKYO-1', 'https://example.com/member/h-tokyo'),
  ('ホテル椿山荘東京', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 89600, 71700, 'H-TOKYO-2', 'https://example.com/member/h-tokyo'),
  ('東京スカイツリー', '入場（大人1名）', null, null, null, 1, 0, 1, 3100, 2300, 'L-TOKYO-1', 'https://example.com/member/l-tokyo'),
  ('横浜ベイホテル東急', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 44000, 28600, 'H-YOKOHAMA-1', 'https://example.com/member/h-yokohama'),
  ('横浜ベイホテル東急', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 61600, 45000, 'H-YOKOHAMA-2', 'https://example.com/member/h-yokohama'),
  ('横浜・八景島シーパラダイス', '入場（大人1名）', null, null, null, 1, 0, 1, 3500, 2600, 'L-YOKOHAMA-1', 'https://example.com/member/l-yokohama'),
  ('東府や Resort & Spa-Izu', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 50000, 36000, 'H-IZU-1', 'https://example.com/member/h-izu'),
  ('東府や Resort & Spa-Izu', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 70000, 56000, 'H-IZU-2', 'https://example.com/member/h-izu'),
  ('伊豆シャボテン動物公園', '入場（大人1名）', null, null, null, 1, 0, 1, 2800, 2100, 'L-IZU-1', 'https://example.com/member/l-izu'),
  ('ハイランドリゾート ホテル＆スパ', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 34000, 24500, 'H-FUJIGOKO-1', 'https://example.com/member/h-fujigoko'),
  ('ハイランドリゾート ホテル＆スパ', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 47600, 38100, 'H-FUJIGOKO-2', 'https://example.com/member/h-fujigoko'),
  ('富士急ハイランド', '入場（大人1名）', null, null, null, 1, 0, 1, 6000, 4500, 'L-FUJIGOKO-1', 'https://example.com/member/l-fujigoko'),
  ('ハイアット セントリック 金沢', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 34000, 22100, 'H-KANAZAWA-1', 'https://example.com/member/h-kanazawa'),
  ('ハイアット セントリック 金沢', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 47600, 34700, 'H-KANAZAWA-2', 'https://example.com/member/h-kanazawa'),
  ('金沢21世紀美術館', '入場（大人1名）', null, null, null, 1, 0, 1, 1400, 1000, 'L-KANAZAWA-1', 'https://example.com/member/l-kanazawa'),
  ('本陣平野屋 花兆庵', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 46000, 29900, 'H-TAKAYAMA-1', 'https://example.com/member/h-takayama'),
  ('本陣平野屋 花兆庵', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 64400, 47000, 'H-TAKAYAMA-2', 'https://example.com/member/h-takayama'),
  ('飛騨の里', '入場（大人1名）', null, null, null, 1, 0, 1, 700, 500, 'L-TAKAYAMA-1', 'https://example.com/member/l-takayama'),
  ('下呂温泉 水明館', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 40000, 26000, 'H-GERO-1', 'https://example.com/member/h-gero'),
  ('下呂温泉 水明館', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 56000, 40900, 'H-GERO-2', 'https://example.com/member/h-gero'),
  ('下呂温泉合掌村', '入場（大人1名）', null, null, null, 1, 0, 1, 800, 600, 'L-GERO-1', 'https://example.com/member/l-gero'),
  ('名古屋マリオットアソシアホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 40000, 24800, 'H-NAGOYA-1', 'https://example.com/member/h-nagoya'),
  ('名古屋マリオットアソシアホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 56000, 39200, 'H-NAGOYA-2', 'https://example.com/member/h-nagoya'),
  ('レゴランド・ジャパン', '入場（大人1名）', null, null, null, 1, 0, 1, 6000, 4500, 'L-NAGOYA-1', 'https://example.com/member/l-nagoya'),
  ('城崎温泉 西村屋本館', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 70000, 43400, 'H-KINOSAKI-1', 'https://example.com/member/h-kinosaki'),
  ('城崎温泉 西村屋本館', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 98000, 68600, 'H-KINOSAKI-2', 'https://example.com/member/h-kinosaki'),
  ('城崎マリンワールド', '入場（大人1名）', null, null, null, 1, 0, 1, 2900, 2200, 'L-KINOSAKI-1', 'https://example.com/member/l-kinosaki'),
  ('有馬温泉 兵衛向陽閣', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 44000, 28600, 'H-KOBE-1', 'https://example.com/member/h-kobe'),
  ('有馬温泉 兵衛向陽閣', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 61600, 45000, 'H-KOBE-2', 'https://example.com/member/h-kobe'),
  ('神戸どうぶつ王国', '入場（大人1名）', null, null, null, 1, 0, 1, 2200, 1600, 'L-KOBE-1', 'https://example.com/member/l-kobe'),
  ('ホテル京阪 ユニバーサル・タワー', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 30000, 18600, 'H-OSAKA-1', 'https://example.com/member/h-osaka'),
  ('ホテル京阪 ユニバーサル・タワー', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 42000, 29400, 'H-OSAKA-2', 'https://example.com/member/h-osaka'),
  ('ユニバーサル・スタジオ・ジャパン', '入場（大人1名）', null, null, null, 1, 0, 1, 8600, 6400, 'L-OSAKA-1', 'https://example.com/member/l-osaka'),
  ('奈良ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 40000, 28800, 'H-NARA-1', 'https://example.com/member/h-nara'),
  ('奈良ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 56000, 44800, 'H-NARA-2', 'https://example.com/member/h-nara'),
  ('奈良国立博物館', '入場（大人1名）', null, null, null, 1, 0, 1, 700, 500, 'L-NARA-1', 'https://example.com/member/l-nara'),
  ('志摩観光ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 56000, 34700, 'H-ISE-1', 'https://example.com/member/h-ise'),
  ('志摩観光ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 78400, 54900, 'H-ISE-2', 'https://example.com/member/h-ise'),
  ('志摩スペイン村', '入場（大人1名）', null, null, null, 1, 0, 1, 5800, 4400, 'L-ISE-1', 'https://example.com/member/l-ise'),
  ('ホテル川久', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 50000, 35000, 'H-SHIRAHAMA-1', 'https://example.com/member/h-shirahama'),
  ('ホテル川久', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 70000, 54600, 'H-SHIRAHAMA-2', 'https://example.com/member/h-shirahama'),
  ('アドベンチャーワールド', '入場（大人1名）', null, null, null, 1, 0, 1, 5300, 4000, 'L-SHIRAHAMA-1', 'https://example.com/member/l-shirahama'),
  ('玉造温泉 長楽園', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 40000, 26000, 'H-MATSUE-1', 'https://example.com/member/h-matsue'),
  ('玉造温泉 長楽園', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 56000, 40900, 'H-MATSUE-2', 'https://example.com/member/h-matsue'),
  ('足立美術館', '入場（大人1名）', null, null, null, 1, 0, 1, 2600, 2000, 'L-MATSUE-1', 'https://example.com/member/l-matsue'),
  ('宮島 錦水館', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 46000, 29900, 'H-HIROSHIMA-1', 'https://example.com/member/h-hiroshima'),
  ('宮島 錦水館', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 64400, 47000, 'H-HIROSHIMA-2', 'https://example.com/member/h-hiroshima'),
  ('宮島水族館 みやじマリン', '入場（大人1名）', null, null, null, 1, 0, 1, 1420, 1100, 'L-HIROSHIMA-1', 'https://example.com/member/l-hiroshima'),
  ('道後温泉 ふなや', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 44000, 31700, 'H-DOGO-1', 'https://example.com/member/h-dogo'),
  ('道後温泉 ふなや', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 61600, 49300, 'H-DOGO-2', 'https://example.com/member/h-dogo'),
  ('松山城', '入場（大人1名）', null, null, null, 1, 0, 1, 520, 400, 'L-DOGO-1', 'https://example.com/member/l-dogo'),
  ('杉乃井ホテル', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 30000, 18600, 'H-BEPPU-1', 'https://example.com/member/h-beppu'),
  ('杉乃井ホテル', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 42000, 29400, 'H-BEPPU-2', 'https://example.com/member/h-beppu'),
  ('別府地獄めぐり', '入場（大人1名）', null, null, null, 1, 0, 1, 2200, 1600, 'L-BEPPU-1', 'https://example.com/member/l-beppu'),
  ('ホテルニュー長崎', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 30000, 21000, 'H-NAGASAKI-1', 'https://example.com/member/h-nagasaki'),
  ('ホテルニュー長崎', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 42000, 32800, 'H-NAGASAKI-2', 'https://example.com/member/h-nagasaki'),
  ('ハウステンボス', '入場（大人1名）', null, null, null, 1, 0, 1, 7600, 5700, 'L-NAGASAKI-1', 'https://example.com/member/l-nagasaki'),
  ('ANAインターコンチネンタル石垣リゾート', 'スタンダード（2食付）', '洋室', '2食付き', 'standard', 2, 0, 1, 52000, 33800, 'H-ISHIGAKI-1', 'https://example.com/member/h-ishigaki'),
  ('ANAインターコンチネンタル石垣リゾート', 'デラックス（2食付）', '和洋室', '2食付き', 'deluxe', 2, 0, 1, 72800, 53100, 'H-ISHIGAKI-2', 'https://example.com/member/h-ishigaki'),
  ('川平湾グラスボート', '入場（大人1名）', null, null, null, 1, 0, 1, 1300, 1000, 'L-ISHIGAKI-1', 'https://example.com/member/l-ishigaki')
) as v(menu_name, name, room_type, meal, grade, adults, children, nights, list_price, benefit_price, coupon_code, member_url)
join bts_app.tenants t on t.code = 'sample'
join bts_app.menus m on m.tenant_id = t.id and m.name = v.menu_name and m.deleted_at is null
where not exists (select 1 from bts_app.plans p where p.menu_id = m.id and p.name = v.name and p.deleted_at is null);

-- ④ 宿の外部サイトの評価（006 と同じく仮の値。楽天から取れたら上書きされる）
update bts_app.menus m set external_rating = v.rating, external_review_count = v.cnt, external_rating_source = 'dummy'
from (values
  ('新富良野プリンスホテル', 4.2, 1650),
  ('JRタワーホテル日航札幌', 4.5, 2380),
  ('登別温泉 第一滝本館', 4.1, 3020),
  ('ラビスタ函館ベイ', 4.6, 2910),
  ('星野リゾート 奥入瀬渓流ホテル', 4.4, 1280),
  ('仙台国際ホテル', 4.2, 1530),
  ('蔵王国際ホテル', 4.3, 960),
  ('星野リゾート 磐梯山温泉ホテル', 4.1, 1120),
  ('ホテルエピナール那須', 4.3, 2140),
  ('日光金谷ホテル', 4.3, 870),
  ('草津ナウリゾートホテル', 4.0, 1890),
  ('ホテル椿山荘東京', 4.6, 1520),
  ('横浜ベイホテル東急', 4.5, 2260),
  ('東府や Resort & Spa-Izu', 4.5, 890),
  ('ハイランドリゾート ホテル＆スパ', 4.2, 1740),
  ('ハイアット セントリック 金沢', 4.5, 1310),
  ('本陣平野屋 花兆庵', 4.6, 1020),
  ('下呂温泉 水明館', 4.4, 1860),
  ('名古屋マリオットアソシアホテル', 4.5, 2050),
  ('城崎温泉 西村屋本館', 4.6, 640),
  ('有馬温泉 兵衛向陽閣', 4.3, 1560),
  ('ホテル京阪 ユニバーサル・タワー', 4.3, 2730),
  ('奈良ホテル', 4.4, 980),
  ('志摩観光ホテル', 4.5, 740),
  ('ホテル川久', 4.5, 1180),
  ('玉造温泉 長楽園', 4.2, 860),
  ('宮島 錦水館', 4.5, 1070),
  ('道後温泉 ふなや', 4.4, 930),
  ('杉乃井ホテル', 4.2, 3480),
  ('ホテルニュー長崎', 4.4, 1430),
  ('ANAインターコンチネンタル石垣リゾート', 4.5, 1890)
) as v(name, rating, cnt)
join bts_app.tenants t on t.code = 'sample'
where m.tenant_id = t.id and m.name = v.name
  and coalesce(m.external_rating_source, 'dummy') = 'dummy';
